### ISSUE TITLE
Cannot Edit Challenge

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#1024]
A user reported an issue where they were unable to edit their challenge created in Work Manager.

Here are the available details:
Challenge URL: https://challenges.topcoder.com/projects/26572/challenges/07596fc0-961b-471b-aca9-0932501ef594/view
User: Tomoya Kurashige (this is the user's name, not handle). This user is a client who is seeking to launch a challenge themselves. 
Issue was originally reported to Topcoder Support in ticket 76330.

**Comment by vikasrohit** [comment]
@acshields it is happening because resource api is not returning any resource for the challenge. There is an issue logged for this https://github.com/topcoder-platform/resources-api/issues/56 which is closed after dev testing by developer, but I am not sure if that is deployed on prod yet or not. I have asked the same there, but haven't received any update yet. My guess is that, after that fix is on prod, this user should not face this issue.

**Comment by vikasrohit** [comment]
@acshields can we close it now?
