### ISSUE TITLE
Default Billing Account: Update V5 Challenge API to read V5 Projects API & Add Checks

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#1042]
### Update 1
Update V5 Challenge API to read the V5 Projects API, instead of the V3 Projects API

### Update 2
Add in checks to ensure that the following conditions are met before a challenge or task can be activated against that billing account:
- Billing Account = Active
- Project = Active
- User activating the challenge or task is joined to the project

**Comment by acshields** [comment]
@rootelement - when do you think you will be able to get this one done?

**Comment by drasticdpk** [comment]
@vikasrohit, please assist here to verify this issue since it is more related to backend.
![image](https://user-images.githubusercontent.com/25297859/108828192-a670ab00-75ee-11eb-8549-465a380bb892.png)

**Comment by vikasrohit** [comment]
@drasticdpk it is not about front making api calls. One of the backend systems is currently using v3 projects api to fetch the Billing Account info when launching the challenge and we are planning to move it to using v5. Its impact would be that when you are launching a challenge from WM, you would be able to launch it even if there is no BA attached to the project in Direct but now BA has to be attached to the Connect Project.
However, having said that, the changes are reverted in production because we didn't have any way to set BA on a Connect Project in Projects App until today's release. So, you won't be able to verify it till we again release these changes. We will let you know when it is ready to be verified. We are planning to do it today's itself.

**Comment by drasticdpk** [comment]
Thank you @vikasrohit  for the info.

**Comment by vikasrohit** [comment]
Moved it out of 0.5.2 to next planned release as we are still not able to decide if we can go ahead with these changes.

**Comment by vikasrohit** [comment]
This one is deployed by @rootelement some time ago. Closing. Please reopen it if I have missed something.
