### ISSUE TITLE
Dev Env - Sync issue WM/OR/Community app

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#1242]
REGISTRANTS  and SUBMISSIONS  list are missing on OR, so unable to verify complete flow.

**Challenge**  : https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30059862

**Reference** 
![image](https://user-images.githubusercontent.com/25297859/135847798-09057b3d-dcc7-435d-bf96-49bf6e91ebb5.png)

**Comment by ThomasKranitsas** [comment]
This is not a sync issue.. Calling the API to register the resource via postman throws 403 Forbidden with the following error:

```
{
    "id": "-696c5d36:17c39b71265:2246",
    "result": {
        "success": true,
        "status": 403,
        "metadata": null,
        "content": "You should agree with all terms of use."
    },
    "version": "v3"
}
```

**Comment by ThomasKranitsas** [comment]
<img width="1464" alt="Screenshot 2021-10-04 at 3 34 58 PM" src="https://user-images.githubusercontent.com/4612921/135852218-a7781b70-2ce0-42ed-9330-59863c54a9a4.png">

It seems like the member has agreed to the term on the V5 API but that information is missing from legacy. That may be because of a temporary outage of the processor that's backfilling legacy or a legacy API outage

**Comment by ThomasKranitsas** [comment]
@drasticdpk can you please register a new account or try with another user to see if it will work correctly?

**Comment by coderhacker** [comment]
linking this issue here which is blocking pureV5 testing https://github.com/topcoder-platform/challenge-autopilot/issues/13.

Here is more finding. 
1. getting this error when editing the same challenge https://challenges.topcoder-dev.com/projects/18798/challenges/9cc0d8c6-7ebe-4c73-b341-ab3f92004193/view
![image](https://user-images.githubusercontent.com/62358241/135853306-232e4f0c-5719-476b-9524-933d2bc683d6.png)
2. when clicking on OR link it's through this error
https://challenges.topcoder-dev.com/projects/18798/challenges/9cc0d8c6-7ebe-4c73-b341-ab3f92004193/view
![image](https://user-images.githubusercontent.com/62358241/135853444-1379f97d-1423-4fb2-9750-7e4eb0791e46.png)

**Comment by ThomasKranitsas** [comment]
The error is expected.

FYI Design challenges are not supported by WM. Only the new V5 Design challenges are supported but that version of the WM is not deployed right now.

**Comment by ThomasKranitsas** [comment]
I'm going to close this issue as it's not a valid issue
