### ISSUE TITLE
Tasks should only have 1 prize

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/work-manager#691]
The challenges of type `TASK` should only have 1 prize.
The `Add new prize` button should be hidden if the challenge is a `TASK`

**Comment by vikasrohit** [comment]
@ThomasKranitsas does any thing fails in the processors if we have more than one prizes for TASK?
I think for the first release we can still have it as is because we can expect first users (tc employees) to know about this fact and practically they won't add more than one challenge prize for a TASK.

**Comment by vikasrohit** [comment]
Increasing the priority to P1 assuming that it is causing a failure in legacy processor and which in turn causing legacy project not being created.

**Comment by ThomasKranitsas** [comment]
@vikasrohit the processor does not fail. It's just invalid UX. We can set it back to `P2`

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/99638737-06a0ff80-2a8a-11eb-9423-b07ebb16c7fc.png)
