### ISSUE TITLE
Unable to Navigate challenge to OR/Direct app

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#807]
**Steps**
1. Go to https://challenges.topcoder.com/projects/24943/challenges
2. Click on OR/Direct link of any challenge 

**Reference**
![image](https://user-images.githubusercontent.com/25297859/93082520-c9e31180-f6b0-11ea-8393-10655bb47cfb.png)
![image](https://user-images.githubusercontent.com/25297859/93082548-d4051000-f6b0-11ea-9eaf-dc38b85af393.png)

**Environment** : Production

**Comment by vikasrohit** [comment]
Is it happening for every challenge @drasticdpk @codejamtc? I would like to reduce the priority if it is happening for only select challenges.
fyi @lakshmiathreya

**Comment by codejamtc** [comment]
@vikasrohit For me - All the available challenges

![image](https://user-images.githubusercontent.com/42398485/93163578-1e9c8180-f6dd-11ea-8996-943861fb2273.png)

**Comment by lakshmiathreya** [comment]
@vikasrohit it is working only for Admin users. Even for me - my non Admin users are unable to navigate to OR/Direct.

**Comment by vikasrohit** [comment]
@lakshmiathreya @codejamtc @drasticdpk it is happening because when your users were added as copilot to the Connect project, legacy project processor was not able to add the same user to the legacy project (direct app) and the reason for that was `Given user: 23278999 is not in the copilot pool` (for codejam) which I dug out from logs. So, I don't think we can fix this issue permanently but for now we can add copilots to the project team in Direct which I did for this specific project.
@lakshmiathreya this is classic example of what I was worried about when it comes to async legacy processors, we don't have feedback of what went wrong and when.

**Comment by drasticdpk** [comment]
Verified on Prod Env. 
Working as expected.

**Comment by lakshmiathreya** [comment]
@vikasrohit seems like this will be an accepted workaround for now for reasons explained by you. @drasticdpk @codejamtc pls verify and change priority appropriately.

**Comment by lakshmiathreya** [comment]
@vikasrohit should we log a new Issue to track this fix in Legacy Project Processor?

**Comment by vikasrohit** [comment]
@lakshmiathreya we can log a separate issue for tracking purposes, however, I don't see the feasible fix for this problem. We may reduce the occurrence of the issue by removing the restrictions around copilot addition in Direct app (which itself is not easy task considering it involves the legacy apps) or can work on some kind of notification system which can alert users (may be the user who added copilot) that it failed to sync the user to legacy app.
