### ISSUE TITLE
[prod] Copilot unable to update Challenge Spec

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/work-manager#821]
**Steps**
1. Create new challenge from WM and launch it. 
2. Try to edit challenge spec.

**Reference**
 Video  : https://monosnap.com/file/juKmLKvkSRnGszEou9SkmzGuC13EDM

![image](https://user-images.githubusercontent.com/25297859/93449790-e53e5e80-f8f4-11ea-8007-894f410a1114.png)

**Comment by vikasrohit** [comment]
@rootelement @ThomasKranitsas this is happening because of https://github.com/topcoder-platform/challenge-api/blob/e0cc722a3d26c70190473ee15b1d742931a535c2/src/services/ChallengeService.js#L1162 which says that it allows for copilots but I am not able to find any check which allows copilots there. I only allows the creator of challenge to edit the challenge.

@drasticdpk you can avoid this error for now if you can create a challenge yourself, please use your created challenges for testing update specific test cases.

**Comment by drasticdpk** [comment]
@vikasrohit ,
I have created new challenge and launch it successfully. However I got the same issue while editing the spec.

Reference :
https://challenges.topcoder.com/projects/24943/challenges/a4875f6a-539b-4129-a03d-729440b5bb1b/view

![image](https://user-images.githubusercontent.com/25297859/93591679-851cea80-f9d0-11ea-9485-e09237af8a6b.png)

![image](https://user-images.githubusercontent.com/25297859/93591768-b2699880-f9d0-11ea-8bcd-f5ad640aaa15.png)

**Comment by ThomasKranitsas** [comment]
@drasticdpk @vikasrohit can you please confirm the WM creates a `Copilot` resource for the copilot when creating a challenge?

**Comment by drasticdpk** [comment]
@ThomasKranitsas ,
While creating the challenge, I have selected my acc as copilot. However it is not reflected on edit screen.

Reference : 
![image](https://user-images.githubusercontent.com/25297859/93592830-98c95080-f9d2-11ea-9396-85073b9a67a7.png)

**Comment by vikasrohit** [comment]
> @drasticdpk @vikasrohit can you please confirm the WM creates a `Copilot` resource for the copilot when creating a challenge?

Yes @ThomasKranitsas, WM is creating Copilot resource, however, in dev legacy resource processor was stuck because of https://github.com/topcoder-platform/legacy-challenge-resource-processor/issues/13 which might be causing copilot resources not added to legacy challenges. However, I am not sure what is happening in prod as processor seems to be working fine in prod.

Just curious @ThomasKranitsas when https://github.com/topcoder-platform/challenge-api/blob/e0cc722a3d26c70190473ee15b1d742931a535c2/src/services/ChallengeService.js#L1162 is not checking for copilot resources, how the authorization is working for copilots in this case?

**Comment by ThomasKranitsas** [comment]
@vikasrohit please check https://github.com/topcoder-platform/challenge-api/blob/develop/src/services/ChallengeService.js#L1164-L1165 which is the latest version. This allows any resource with full access to modify a challenge.

**Comment by vikasrohit** [comment]
@drasticdpk @codejamtc please test it in dev.

**Comment by codejamtc** [comment]
@drasticdpk I am able to edit the challenge now but please double-check from your end too, Thanks cc @vikasrohit


[3.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5262421/3.zip)
![image](https://user-images.githubusercontent.com/42398485/93902291-028c7780-fcbd-11ea-9286-4b8b32922264.png)

**Comment by drasticdpk** [comment]
Thank  you @codejamtc .  Here I am still not sure this issue is fixed or not. 
This is my understanding :
1. Challenge Spec  auto Update   > If any thing changes it has to auto update like google sheet.
2. For other than spec filed user has to click `Save draft button`

May I know the logic behind it `<br /><br /><h2>Final Submission Guidelines</h2>Please read above`. After adding it some time I am having the issue.
 FYI Since it is not reflecting on this challenge :
https://challenges.topcoder-dev.com/projects/9074/challenges/3039eba1-d987-44bd-83c0-98a475e3f9b7/view

Reference : 
[Copilot unable to update Challenge Spec.mp4.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5265517/Copilot.unable.to.update.Challenge.Spec.mp4.zip)

cc @vikasrohit

**Comment by vikasrohit** [comment]
Yes, your understanding is correct @drasticdpk 

You can ignore the augmentations of `Please read above.` in the spec description, it is being done by the legacy migration script. We can log it as non P0/P1 and revisit it later. Most probably it is as per the expectations.

From your demo video, I can see that the original issue itself is fixed, however, there is some other issue which is causing the success modal to not appear and I think that is already logged here #811

**Comment by drasticdpk** [comment]
Ok Noted @vikasrohit .

**Comment by sandhiyakavi** [comment]
Verified on Prod.Working as expected.

[issue#821.zip](https://github.com/topcoder-platform/work-manager/files/5572491/issue.821.zip)
