### ISSUE TITLE
Copilot and prize values reset after saving 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#826]
[2.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5268038/2.zip)

### Steps to reproduce the problem

1. Open https://challenges.topcoder-dev.com/ and login as Admin
2. Select a project from the list 'Test v5 {codejam} - 0001'
3. Create a Dev challenge with all the details and save as draft
4. Click Edit
5. Change the name, public specification, add two prizes and change the copilot fee
6. Click Save Draft
7. Check the prizes and copilot fee

### Actual behavior
- Copilot and prize values reset after saving 

### Expected behavior
- Should not reset

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 85.0.4183.83
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `copilot_codejam`

**Comment by vikasrohit** [comment]
@lakshmiathreya @codejamtc marking ready for QA because the underlying issue with legacy-challenge-resource-processor is supposed to be fixed now.

**Comment by vikasrohit** [comment]
@vikasrohit @lakshmiathreya @rootelement I still faced this issue on dev today for challenge http://local.topcoder-dev.com:3000/projects/16573/challenges/85c184c0-9bf8-46de-ad51-4f4dfeae630e/view. It happened after I closes the task in v5, however, it went back to Active after some time because Autopilot is not able to close the `Iterative Review` phase for the challenge in legacy. And when it is moved back to Active, it lost the Copilot resource attached to the challenge/task.
