### ISSUE TITLE
Implement Default Forums Object

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/work-manager#845]
When a challenge is saved as draft, please add these properties to the challenge object for a challenge type or f2f type to trigger a forum create. We can then work to make this configurable, including track/type ids that have this enabled by default, how tasks don't create forums, etc.

This is just the first step.

Example object:
```
"challenge.discussions": [
  {
    "name": "My Forum Name",
    "type": "challenge",
    "provider": "vanilla"
  }
]
```

Reference challenge api issue:
https://github.com/topcoder-platform/challenge-api/issues/290#issuecomment-696921827

**NOTE**  
The challenge API will not accept this object until this PR is merged into develop. I'm estimating daytime Weds Sept 30th EDT.
https://github.com/topcoder-platform/challenge-api/pull/309

**Comment by rootelement** [comment]
@vikasrohit i assigned this to you for now, it's up to you if you want to task this out and get a PR pending for dev so we can add this at the same time.

**Comment by maxceem** [comment]
@vikasrohit this is done via PR https://github.com/topcoder-platform/challenge-engine-ui/pull/846. This PR can be already merged if you like because API doesn't complain about submitting `discussions` property even now.

The forum name is formatted as `${challenge.name} Discussion`, but let me know if it should be different.
