### ISSUE TITLE
Add an Activate button to the challenge details screen for Draft challenges

### ISSUE THREAD

**Issue by mtwomey** [topcoder-platform/work-manager#867]

**Comment by vikasrohit** [comment]
You mean, on view screen?

**Comment by vikasrohit** [comment]
We already have an Activate button on listing page for quick access, but we can still discuss.

**Comment by vikasrohit** [comment]
@mtwomey it is deployed to production.

**Comment by drasticdpk** [comment]
@vikasrohit , 
We can see there is "Launch" button instead of Active. Yes  through this button user can activate the challenge. 

**reference** 
![image](https://user-images.githubusercontent.com/25297859/101491541-fb0b6f00-398b-11eb-91cb-33c0e602cbd0.png)

@vikasrohit So, this logic also should be available here, right ? 
please confirm.

**Comment by vikasrohit** [comment]
> We can see there is "Launch" button instead of Active

Yes that is okay.

> @vikasrohit So, this logic also should be available here too, right ?

yes, it is.

**Comment by drasticdpk** [comment]
@vikasrohit  can we have **View Details** text at center of those button ?

![image](https://user-images.githubusercontent.com/25297859/101755360-e0a4d300-3afc-11eb-83cf-0e155bba5614.png)

**Comment by vikasrohit** [comment]
@drasticdpk it is already in center of the view. It is only the right side has 3 buttons while left one has only 2. :)
