### ISSUE TITLE
 Error while creating a Task

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/work-manager#893]
[1.zip](https://github.com/topcoder-platform/challenge-engine-ui/files/5485566/1.zip)

### Steps to reproduce the problem

1. Open [Dev Environment](https://challenges.topcoder-dev.com/) and login as Copilot
2. Select a project from the list '[Test v5 {codejam} - 0001](https://challenges.topcoder-dev.com/projects/16604/challenges)'
3. Create a Dev Task
4. Fill all the mandatory details and Click Save as draft

### Actual behavior
- Error while creating a Task

### Expected behavior
- Should not display such error and user should be able to create a task without any issue

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome  86.0.4240.111
**- User role (client, copilot or manager):** Copilot
**- Account used:**  `TCConnCopilot`

**Comment by vikasrohit** [comment]
@codejamtc it must be because of invalid session, I mean you might need to refresh the page before creating challenge. UI is handling the api error gracefully, it might a 403 thrown by api (in case of incorrect token or inability to refresh the token) or any other error. But nothing has changed technically in UI or even in the API for the creation part. It must be temporary.

**Comment by coderhacker** [comment]
https://user-images.githubusercontent.com/62358241/119331855-76947a80-bca5-11eb-8d55-d32e4fe74b32.mp4
