### ISSUE TITLE
Enable Launch as Activate button on Challenge Edit page only when legacy is available

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/work-manager#933]
As of now we are showing the `Launch as Active` button always no matter if the legacy challenge is created or not which confuses users. So, we need to make that button disabled and greyed out with our custom tooltip (saying the same message which we are showing for the Direct and OR links on top).

**Comment by vikasrohit** [comment]
@acshields @mtwomey fyi, created this issue to track what we discussed in our call yesterday

**Comment by maxceem** [comment]
@vikasrohit done via PR https://github.com/topcoder-platform/work-manager/pull/934

**Comment by vikasrohit** [comment]
@maxceem I think you fixed the Launch button on Challenge Edit page (that is a good fix), however, I created issue for fixing the Activate button on the listing page. Can you please do fix that button, which comes on hover of list item, now? Feel free to create separate issue for logging the work.

**Comment by maxceem** [comment]
@vikasrohit at the moment the logic here is like this:
![image](https://user-images.githubusercontent.com/146016/101485205-815f8b00-3963-11eb-8143-f2d62742aad2.png)

- Button "Active" is not shown if legacy is not created
- Direct and OR links are showing error message if we click them when legacy is not created:

   ![image](https://user-images.githubusercontent.com/146016/101485317-a8b65800-3963-11eb-8996-a0d333bc8934.png)

As per this task, instead of hiding "Acitve" button we have to make it disabled with a tooltip "Legacy project is not yet created".

Should we do the same for Direct and OR links?

But note, that we also showing these buttons for the NEW challenges:

![image](https://user-images.githubusercontent.com/146016/101485614-0fd40c80-3964-11eb-9b70-6db24c28dc87.png)

So we show them disabled in the DRAFT list when there is no legacy, should we show them the same way for new? Or hide at all. I think it doesn't make sense to show message "Legacy project is not yet created" for NEW, as legacy is not suppose to be create for NEW.

**Comment by vikasrohit** [comment]
> Button "Active" is not shown if legacy is not created

I can see the `Activate` button on production for a challenge which is in Draft and still don't have legacy challenge created yet.

> Should we do the same for Direct and OR links?

If that is easy to do with them, please do it (feel free to log separate issue for that). And we can hide those links on the New tab to avoid confusion.

**Comment by drasticdpk** [comment]
We are having **Active** before legacy is available .

Reference 

![image](https://user-images.githubusercontent.com/25297859/101490326-4c1a6380-398a-11eb-95b7-153df5f483f2.png)

**Comment by drasticdpk** [comment]
@vikasrohit So this issue will be invalid, right ?
https://github.com/topcoder-platform/work-manager/issues/942

**Comment by maxceem** [comment]
@drasticdpk not really. We would still show a message `Legacy project is not yet created` but a different way.

**Comment by maxceem** [comment]
@vikasrohit I've created a separate issue https://github.com/topcoder-platform/work-manager/issues/943

So I guess we can rename this issue to represent the actual job done here and close it.

**Comment by vikasrohit** [comment]
@drasticdpk I am closing this one after updating the description of the issue as the work done under this story is already verified and working fine on prod. @maxceem has created separate issue #943 for the concern I raised above, so we would verify those missing pieces there.
