### ISSUE TITLE
Move "Close Task" to View Screen

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/work-manager#944]
Much like the Launch button on the challenge view screen, the Close Task button should be visible on the View screen for a challenge (and possibly the list view as well) when the scenario fits. It's not intuitive to have it on the Edit screen.

Also, i suggest making the Close Task button Green instead of Red. Red = stop/delete. You're successfully closing the task, the button should denote that.

![Screen Shot 2020-12-08 at 10 15 45 AM](https://user-images.githubusercontent.com/5400156/101502073-83632300-393e-11eb-8c7e-bd7927daa3ef.png)

**Comment by vikasrohit** [comment]
Agreed @rootelement and in fact that is why I was in favour of design update first to have the nice UX because current version is not at all user friendly and it need a lot of improvements which will cause major refactoring in the application which in turn would have required heavy regression testing etc.
Instead of replicating all of the edit page's functionality on the read only page, we should be skipping the view page altogether and directly take use to the edit page. It is tricky and non optimized to bring all edit features to the read only page.

But, I guess because now I have already wired the view component to bring edit features, I can add the close task as well there.

**Comment by vikasrohit** [comment]
@rootelement @lakshmiathreya @drasticdpk it should be live on prod in 15 minutes

**Comment by drasticdpk** [comment]
Verified.
![image](https://user-images.githubusercontent.com/25297859/101760161-9d4d6300-3b02-11eb-9934-cb20b80f04ab.png)
![image](https://user-images.githubusercontent.com/25297859/101760193-ab9b7f00-3b02-11eb-99ec-11f738ce5d83.png)

Note : @vikasrohit , since there is design issue, if we open the window in <= 1300px.

![image](https://user-images.githubusercontent.com/25297859/101760419-ef8e8400-3b02-11eb-93a8-9ba4863bc5e2.png)

**Comment by vikasrohit** [comment]
That is okay for now @drasticdpk, new designs are due very soon.
