### ISSUE TITLE
Relabel "Active Challenges" to "All Work" in Left Sidebar

### ISSUE THREAD

**Issue by acshields** [topcoder-platform/work-manager#953]
<img width="180" alt="Screen Shot 2020-12-09 at 12 50 12 PM" src="https://user-images.githubusercontent.com/41118149/101673815-43bf3880-3a1d-11eb-821a-9d47521006f0.png">

**Comment by vikasrohit** [comment]
@acshields actually as of now we don't show all work there, I mean when user clicks on `Active Challenges` right now we ask them to select the project. @mtwomey suggested some time ago to show all challenges instead on that page. In other words, if we can show the challenge listing page without a project filter on that page. So, if go with that implementation (that would some time to implement and we can not target it for 15th release and it might not make sense to do that considering the new designs as well), that we can name it as `All Work` otherwise we might want to rename it something more related e.g. `Change Project`.

**Comment by acshields** [comment]
@vikasrohit - "Projects" would work for now.

And for reference, I have a design request out right now that will seek to improve the layout of this page, so that it does show "All Work" in a table-view that is easily searchable/filterable, etc. so that:
- The user can see all their work for various projects in a single view, without having to click into each project
- The user can easily search/filter to find the specific things they are looking for

To handle the volume of projects/work shown here, I have also have requested that the design include:
- An "Archived" feature, so projects that have been completed
- A "My Work" vs. "All Work" toggle for Topcoder users

Not something to worry about at this moment, but just sharing for context.

**Comment by drasticdpk** [comment]
Reference 
![image](https://user-images.githubusercontent.com/25297859/101872573-9596c880-3bad-11eb-893b-36bce8dec6b5.png)

**Comment by drasticdpk** [comment]
> To handle the volume of projects/work shown here, I have also have requested that the design include:

> An "Archived" feature, so projects that have been completed
> A "My Work" vs. "All Work" toggle for Topcoder users

@vikasrohit , Do we need to create new ticket for this ?

**Comment by vikasrohit** [comment]
No we don't need any ticket for it. We would have it with new designs requirements.
