### ISSUE TITLE
Show "Save" button after the challenge is launched

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/work-manager#955]
At the moment as soon as we launched the challenge there is no "Save" button to save changes:

![image](https://user-images.githubusercontent.com/146016/101747905-809a3680-3ad4-11eb-9c95-004ef8a6be79.png)

This can be reproduced on PROD and on DEV (if have a billing account).

@vikasrohit, should we fix this?

**Comment by vikasrohit** [comment]
It was intentional for the upcoming release, as we removed the `Save` button to avoid confusion between it and `Save Draft` buttons. However, we might think of showing the Save button only when challenge is not in `Draft` status i.e. when challenge is in `Active` status. Let me ask product managers for it.

**Comment by drasticdpk** [comment]
Verified.

![image](https://user-images.githubusercontent.com/25297859/101873578-4baee200-3baf-11eb-9d22-66585c1d2de0.png)

Save button is working as expected.

![image](https://user-images.githubusercontent.com/25297859/101873638-6b460a80-3baf-11eb-895f-ef385d6f90b0.png)
