### ISSUE TITLE
Markdown Text Editor mess up when combined number and generic list

### ISSUE THREAD

**Issue by dedywahyudi** [topcoder-platform/work-manager#969]
**Describe the bug**
Markdown Text Editor mess up when combined number and generic list

**To Reproduce / Actual Behavior**
1. Create new challenge
2. Fill content with combination number & generic list
3. Check challenge detail page

**Expected behavior**
Challenge page need able to render generic list inside the number list with proper indentation

**Screenshots**
Sample 1:
![Screen Shot 2020-12-11 at 11 56 32](https://user-images.githubusercontent.com/4476442/101867074-f376e080-3bac-11eb-93c0-9689612b8429.png)
![Screen Shot 2020-12-11 at 11 56 49](https://user-images.githubusercontent.com/4476442/101867076-f4a80d80-3bac-11eb-9eb3-707a65b227d2.png)

Sample 2:
![Screen Shot 2020-12-11 at 11 58 57](https://user-images.githubusercontent.com/4476442/101867084-f70a6780-3bac-11eb-847b-9237914d974d.png)
![Screen Shot 2020-12-11 at 11 57 45](https://user-images.githubusercontent.com/4476442/101867081-f671d100-3bac-11eb-8847-0055b9d0a5c0.png)

**Comment by maxceem** [comment]
@vikasrohit @dedywahyudi this issue is not in Work Manager editor. Editor just edit markdown text, but it doesn't render details on the challenge details page. The issue with rendering has to be fixed in Community App https://github.com/topcoder-platform/community-app

By the way, the editor has a preview button, and it shows lists correctly even when nested, see:

![image](https://user-images.githubusercontent.com/146016/103764361-fcc86100-5023-11eb-85d1-ed4495ad5260.png)

**Comment by vikasrohit** [comment]
@acshields fyi, we should move it to Community App.

**Comment by acshields** [comment]
@vikasrohit - sending the link to Oanh for her to manage.

**Comment by acshields** [comment]
Also, removed it from our January work.

**Comment by vikasrohit** [comment]
Can we close it from here @acshields ?

**Comment by acshields** [comment]
@vikasrohit - yes! just closed.
